name: CI

on:
  push:
    branches: [ "main", "setup-github-action" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
        run:
            shell: ${{ matrix.shell }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [g++, cl]
        build_type: [Release]
        include:
          - os: windows-latest
            arch: 'win64_mingw'
            host: 'windows'
            shell: 'msys2 {0}'
            compiler: cl
          - os: ubuntu-latest
            arch: 'gcc_64'
            host: 'linux'
            shell: 'bash'
            compiler: g++
        exclude:
          - os: windows-latest
            compiler: g++
          - os: ubuntu-latest
            compiler: cl

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Install MSYS2
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
        msystem: mingw64
        release: false
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.5.3'
        host: ${{ matrix.host }}
        target: 'desktop'
        arch: ${{ matrix.arch }}
        dir: '${{github.workspace}}/qt'
        install-deps: 'true'     
    
    - name: Configure
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}/lib/cmake
        CMAKE_CXX_COMPILER: ${{ matrix.compiler }}
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DALP_ENABLE_POSITIONING=false -B '${{github.workspace}}'/build

    - name: Build
      run: cmake --build '${{github.workspace}}'/build

    - name: Test
      run: |
        '${{github.workspace}}'/build/sherpa/unittests_sherpa
        '${{github.workspace}}'/build/unittests/unittests_nucleus
        '${{github.workspace}}'/build/unittests_gl/unittests_gl_engine
