name: Emscripten build

on:
  push:
    branches: [ "emscripten-github-action" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup emsdk
      run: |
        git clone https://github.com/juj/emsdk.git
        cd emsdk
        find .
        ./emsdk install latest
        ./emsdk activate latest
        source emsdk_env.sh
        cd ..
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.3'
        host: 'linux'
        target: 'desktop'
        arch: 'wasm_singlethread'

    - name: Configure CMake
      run: |
        chmod +x ${{ env.Qt6_DIR }}/bin/qt-cmake
        qt-cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DQt6_DIR=${{ env.Qt6_DIR }}/lib/cmake/Qt6 -DALP_ENABLE_POSITIONING=false -B '${{github.workspace}}'/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
